### ISSUE TITLE
Clean - Project Navigation Dropdown

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#100]
1. Review #21  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task - it is for masters, but many things will be applicable to this page as well.
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**method 1 - to get project list of current user**

SELECT 
    1 AS [C1], 
    [Extent2].[Id] AS [Id], 
    [Extent2].[Title] AS [Title]
    FROM  [dbo].[ProjectMembership] AS [Extent1]
    INNER JOIN [dbo].[Project] AS [Extent2] ON [Extent1].[ProjectId] = [Extent2].[Id]
    WHERE ([Extent1].[UserId] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)

**Comment by AAndharia** [comment]
![image](https://cloud.githubusercontent.com/assets/2442925/6266703/ea58f07a-b862-11e4-9377-256cf4f58960.png)

It still shows blank section. Please verify all possibility with and without create permission

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

possibility 1 - when user has permission for create project and my projects
dropdown contains 1st link for create project > divider > list of project user involved in

possibility 2 - when user has only permission to create project
dropdown contains only create project link

possibility 3 - when user has only permission for my-projects
dropddown contains only projects in which user involved.

possibility 4 - when user has no permission for create project or my-projects
dropdown hidden to user.

**Comment by AAndharia** [comment]
Verified. Closing.
