### ISSUE TITLE
refresh grid after add & update holiday 

### ISSUE THREAD

**Issue by jmervana** [AAndharia/iManager#49]

**Comment by AAndharia** [comment]
Fix if not already taken care. Assign back to me when done.

**Comment by pasodariya** [comment]
Done Please verify

**Comment by AAndharia** [comment]
this is still not proper, check all logic what data should be loaded when refresh etc.

**Comment by pasodariya** [comment]
This issue already solved please verify.

**Comment by jmervana** [comment]
After add holiday in next year , why I can switch to current year, it should not switch to current year if added holiday is for next year.

**Comment by pasodariya** [comment]
Done

**Comment by jmervana** [comment]
@AAndharia 
I have tested it
