### ISSUE TITLE
Clean CRUD - Permission Codes

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#86]
1. Review #2  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**method 1 - get permission list**
**service method - PermissionService.cs >> SelectAllPermissionCodes**

SELECT 
    [GroupBy1].[A1] AS [C1]
    FROM ( SELECT 
        COUNT(1) AS [A1]
        FROM [dbo].[Permission] AS [Extent1]
    )  AS [GroupBy1]

**method 2 - add permission list**
**service method - PermissionService.cs >> AddPermissionCode**

INSERT [dbo].[Permission]([Id], [Description])
VALUES (@0, @1)

**method 3 - update permission list**
**service method - PermissionService.cs >> UpdatePermissionCode**

UPDATE [dbo].[Permission]
SET [Description] = @0
WHERE ([Id] = @1)

**method 4  - delete permission list**
**service method - PermissionService.cs >> DeletePermissionCode**

DELETE [dbo].[Permission]
WHERE ([Id] = @0)

**Comment by AAndharia** [comment]
Please correct commentings in PermissionService.cs

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
There are still not proper description. Some places where it is using UserId it says Role etc.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Still not proper....

example 
this method AddRemoveUserPermission has this description 
        /// Add or Remove All Permission From Specific Role

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
Check PermissionService - all methods all comments again.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
@prupapara - please verify this once again. If you think now all is good. close this issue.

**Comment by prupapara** [comment]
Verified.
