### ISSUE TITLE
Clean - Project Dashboard

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/iManager#99]
1. Review #20  again, i've added some more details in it, rename files/methods/ etc where required, implement any missing part.
2. Review & Make corrections as per #85 for this task - it is for masters, but many things will be applicable to this page as well.
3. For all controller action methods and services add proper code commenting inside methods and XML comment above methods as well.

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**method 1 - to get project name**

SELECT 
    [Limit1].[C1] AS [C1], 
    [Limit1].[Title] AS [Title]
    FROM ( SELECT TOP (1) 
        [Extent1].[Title] AS [Title], 
        1 AS [C1]
        FROM [dbo].[Project] AS [Extent1]
        WHERE ([Extent1].[Id] = @p__linq__0) AND (@p__linq__0 IS NOT NULL)
    )  AS [Limit1]

**Comment by AAndharia** [comment]
1. I have just added permission info to specs. 
Only user who is member of this project and user with permission of 'my-projects' can access this page. - please implement this. I think you'll need to create a new filter, which can be re-used for other project specific controllers

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
1. isUserInvolvedInProject - wrong naming convension
2. attribute name should be         [IsUserAuthorizedForProject]
3. discuss with me about inheriting IsUserAuthorizeForProject from AuthorizeRole attribute

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
1. isUserInvolvedInProject  - still not corrected
2. ok
3. i've seen what you've implemented here, can't we do code base.Authorize() or something and just write down logic only related to project permission in this filter.?

**Comment by jmervana** [comment]
@AAndharia 
Done please verify

**Comment by AAndharia** [comment]
@jmervana - let us discuss about this.
